import { useGetBarajaRoom, useLeaveBarajaRoom, usePartyAction, type PartyState } from "@workspace/api-client-react";
import { useRouter } from "expo-router";
import React, { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import BoardRoomLobby from "@/components/BoardRoomLobby";
import { useColors } from "@/hooks/useColors";
import { clearBarajaSession, loadBarajaSession, type BarajaSession } from "@/lib/barajaSession";

type Mode = string;
const MODES: Array<{ id: Mode; icon: string; title: string; hint: string }> = [
  { id: "coin", icon: "🪙", title: "Juego de la Moneda", hint: "Lanza, asigna turnos y rebota el bote" },
  { id: "never", icon: "🔥", title: "Yo Nunca", hint: "Modo Risas o Picante · votación anónima" },
  { id: "truth", icon: "🎡", title: "Verdad o Reto", hint: "La ruleta elige víctima y dinámica" },
  { id: "probable", icon: "🎯", title: "Quién es más Probable", hint: "Vota al integrante que encaja más" },
  { id: "five", icon: "⏱️", title: "Regla de 5 Segundos", hint: "Nombra 3 cosas antes de que acabe el tiempo" },
  { id: "king", icon: "👑", title: "El Rey del Trago", hint: "Retos, normas acumulativas y duelos" },
  { id: "taboo", icon: "🤐", title: "Tabú Relámpago", hint: "Adivina sin decir las 3 palabras prohibidas" },
  { id: "bomb", icon: "💣", title: "Bomba Caliente Party", hint: "Responde rápido y pásala antes de explotar" },
  { id: "barco", icon: "🚢", title: "Barco de Chupitos", hint: "Rondas temáticas sin repetir respuestas" },
  { id: "telefono", icon: "📞", title: "Teléfono Roto de Retos", hint: "Pasa consignas secretas de jugador a jugador" },
  { id: "miradas", icon: "👀", title: "Duelo de Miradas Virtual", hint: "Aguanta sin parpadear y vence al rival" },
  { id: "piramide", icon: "🃏", title: "Pirámide de Cartas", hint: "Mayor o menor en rondas escalonadas" },
  { id: "subasta", icon: "🔨", title: "Subasta de Tragos", hint: "Apuesta quién se atreve por el comodín" },
  { id: "dictador", icon: "👑", title: "El Dictador", hint: "Un jugador impone 3 leyes absurdas" },
  { id: "ruleta-alcohol", icon: "🎰", title: "Ruleta Rusa de Alcohol", hint: "Seis vasos virtuales: uno de chupito" },
];
const NEVER_RISAS_BASE = ["He cantado en la ducha", "He perdido el móvil de fiesta", "He hecho ghosting", "He bailado encima de una mesa", "He mandado un audio de 10 minutos", "He fingido conocer una canción", "He llegado tarde a mi propia fiesta", "He pedido comida a las 4 de la mañana", "He confundido una fecha", "He reído en un momento serio", "He hecho karaoke solo", "He usado una app de citas", "He contado un secreto", "He dormido en casa de un amigo", "He hecho algo solo por una apuesta", "He tenido un apodo secreto", "He comprado algo inútil de madrugada", "He hecho una entrada dramática", "He visto una serie entera en un día", "He cambiado de look impulsivamente"];
const NEVER_PICANTE_BASE = ["He besado a alguien en esta sala", "He tenido un crush con un amigo", "He mandado un mensaje y me he arrepentido", "He stalkeado a un ex", "He salido con dos personas a la vez", "He fingido estar enfermo para ligar", "He tenido una cita desastrosa", "He usado una excusa para acercarme a alguien", "He enviado una foto comprometida", "He dicho te quiero sin querer", "He vuelto con mi ex", "He tenido un flechazo instantáneo", "He coqueteado con alguien prohibido", "He ocultado una cita", "He mentido sobre mi edad"];
const NEVER_RISAS = [...NEVER_RISAS_BASE, ...Array.from({ length: 55 }, (_, i) => `${NEVER_RISAS_BASE[i % NEVER_RISAS_BASE.length]} (edición fiesta ${i + 1})`)];
const NEVER_PICANTE = [...NEVER_PICANTE_BASE, ...Array.from({ length: 55 }, (_, i) => `${NEVER_PICANTE_BASE[i % NEVER_PICANTE_BASE.length]} (edición picante ${i + 1})`)];
const PROBABLE = ["¿Quién es más probable que llegue tarde?", "¿Quién se enamora primero?", "¿Quién sobreviviría a un apocalipsis?", "¿Quién se hará viral?", "¿Quién mandará un audio de 10 minutos?", "¿Quién se irá de viaje mañana?", "¿Quién ganará una discusión?", "¿Quién olvidará su propio cumpleaños?"];
const TRUTHS = ["VERDAD: cuenta una anécdota que nadie conozca", "VERDAD: enseña tu última búsqueda", "VERDAD: ¿quién te cae mejor de la sala?"];
const DARES = ["RETO: brinda y canta un estribillo", "RETO: habla con acento durante una ronda", "RETO: haz una pose dramática para la sala"];
const FIVE = ["Nombra 3 marcas de refresco", "Nombra 3 películas de miedo", "Nombra 3 cosas que llevarías a una isla", "Nombra 3 canciones de fiesta", "Nombra 3 excusas para llegar tarde"];
const TABOOS = ["PALABRA: fiesta · PROHIBIDAS: beber, música, amigos", "PALABRA: playa · PROHIBIDAS: arena, mar, verano", "PALABRA: móvil · PROHIBIDAS: pantalla, llamar, mensaje"];
const KING = ["El Rey manda: todos beben", "Regla nueva: nadie puede decir 'sí'", "Duelo: piedra, papel o tijera entre dos jugadores", "Elige a alguien para beber contigo"];
const BOMBS = ["Di 3 ciudades antes de pasar la bomba", "Di 3 animales que vuelan y pásala", "Di 3 palabras que rimen con sol"];

export default function PartyRoomScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const router = useRouter();
  const [session, setSession] = useState<BarajaSession | null>(null); const [hydrated, setHydrated] = useState(false); const [selected, setSelected] = useState<Mode>("coin"); const [query, setQuery] = useState(""); const [spicy, setSpicy] = useState(false);
  useEffect(() => { loadBarajaSession().then((s) => { setSession(s); setHydrated(true); }); }, []);
  const { data: room, isLoading } = useGetBarajaRoom(session?.roomCode ?? "", session?.playerId ?? ""); const party = usePartyAction(); const leave = useLeaveBarajaRoom();
  if (!hydrated || (session && isLoading)) return <View style={styles.loading}><ActivityIndicator color="#FF7A45" /></View>;
  if (!session || !room) return <BoardRoomLobby kind="party" title="Sala Social Party" subtitle="Elige una dinámica y jugadla a pantalla completa." accent="#FF7A45" maxPlayers={12} defaultMaxPlayers={6} onBack="/" />;
  const gs = room.gameState?.type === "party" ? room.gameState : null; if (!gs) return <View style={styles.loading}><ActivityIndicator color="#FF7A45" /></View>;
  const me = session.playerId; const send = (action: "coin" | "prompt" | "vote" | "probable", value?: string, kind?: "incómoda" | "yo-nunca") => party.mutate({ code: room.code, playerId: me, action, value, kind });
  const quit = async () => { await leave.mutateAsync({ code: room.code, playerId: me }); await clearBarajaSession(); router.replace("/"); };
  const prompt = gs.promptText ?? "Elige una tarjeta para empezar"; const votes = Object.values(gs.promptVotes); const yes = votes.filter((v) => v === "sí").length;
  const showPrompt = (text: string, kind: "incómoda" | "yo-nunca" = "incómoda") => send("prompt", text, kind);
  const visibleModes = MODES.filter((m) => `${m.title} ${m.hint}`.toLowerCase().includes(query.toLowerCase()));
  return <View style={[styles.screen, { backgroundColor: colors.background }]}>
    <View style={[styles.catalog, { paddingTop: insets.top + 12 }]}><TextInput value={query} onChangeText={setQuery} placeholder="Buscar dinámica..." placeholderTextColor="#806A94" style={styles.search} /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.selector}>{visibleModes.map((mode) => <Pressable key={mode.id} onPress={() => setSelected(mode.id)} style={[styles.tab, selected === mode.id && styles.activeTab]}><Text style={styles.tabIcon}>{mode.icon}</Text><Text style={[styles.tabText, selected === mode.id && styles.activeText]}>{mode.title}</Text></Pressable>)}</ScrollView></View>
    <ScrollView contentContainerStyle={[styles.container, { paddingBottom: insets.bottom + 30 }]}>
      <View style={styles.header}><View><Text style={styles.kicker}>SALA SOCIAL · 18+</Text><Text style={[styles.title, { color: colors.foreground }]}>🎉 PARTY MODE</Text></View><Pressable onPress={quit} style={styles.exit}><Text style={styles.exitText}>SALIR</Text></Pressable></View>
      <View style={styles.game}><Text style={styles.bigIcon}>{MODES.find((m) => m.id === selected)?.icon}</Text><Text style={styles.gameTitle}>{MODES.find((m) => m.id === selected)?.title}</Text><Text style={styles.hint}>{MODES.find((m) => m.id === selected)?.hint}</Text>
        {selected === "coin" && <><Text style={styles.coin}>{gs.coinSide ? (gs.coinSide === "cara" ? "🙂" : "🔴") : "🪙"}</Text><Text style={styles.prompt}>{gs.coinSide ? `${gs.coinSide.toUpperCase()} · Empieza ${room.players.find((p) => p.id === gs.coinStarterId)?.name ?? "alguien"} · Bote ${gs.sipPot} sorbo(s)` : "Lanza para asignar quién empieza"}</Text><Button label="LANZAR MONEDA" onPress={() => send("coin")} /></>}
        {selected === "never" && <><View style={styles.switch}><Pressable onPress={() => setSpicy(false)} style={[styles.switchButton, !spicy && styles.selectedSwitch]}><Text style={styles.switchText}>RISAS</Text></Pressable><Pressable onPress={() => setSpicy(true)} style={[styles.switchButton, spicy && styles.selectedSwitch]}><Text style={styles.switchText}>PICANTE</Text></Pressable></View><Text style={styles.prompt}>{prompt}</Text><View style={styles.row}><Button label="HE BEBIDO" onPress={() => send("vote", "sí")} /><Button label="PASO" secondary onPress={() => send("vote", "paso")} /></View><Text style={styles.stats}>{votes.length ? `${Math.round(yes / votes.length * 100)}% han bebido · votación anónima en directo` : "0 votos · nadie ve quién votó"}</Text><Button label="NUEVA TARJETA" secondary onPress={() => showPrompt((spicy ? NEVER_PICANTE : NEVER_RISAS)[gs.promptRound % (spicy ? NEVER_PICANTE : NEVER_RISAS).length], "yo-nunca")} /></>}
        {selected === "truth" && <><Text style={styles.prompt}>{gs.promptKind === "incómoda" && gs.promptText ? gs.promptText : "La ruleta elige víctima y dinámica"}</Text><Button label="VERDAD" onPress={() => showPrompt(TRUTHS[gs.promptRound % TRUTHS.length])} /><Button label="RETO" secondary onPress={() => showPrompt(DARES[gs.promptRound % DARES.length])} /></>}
        {selected === "probable" && <><Text style={styles.prompt}>{gs.promptText ?? PROBABLE[0]}</Text><View style={styles.players}>{room.players.map((p) => <Pressable key={p.id} onPress={() => send("probable", `${PROBABLE[gs.promptRound % PROBABLE.length]} → ${p.name}`)} style={styles.player}><Text style={styles.playerText}>{p.avatar} {p.name}</Text></Pressable>)}</View><Text style={styles.stats}>Votación anónima sincronizada · el más votado asume el castigo</Text><Button label="NUEVA AFIRMACIÓN" secondary onPress={() => send("probable", PROBABLE[(gs.promptRound + 1) % PROBABLE.length])} /></>}
        {(selected === "five" || selected === "king" || selected === "taboo" || selected === "bomb") && <><Text style={styles.prompt}>{prompt}</Text><Button label={selected === "five" ? "¡LO HE DICHO!" : selected === "bomb" ? "PASAR BOMBA" : "NUEVO RETO"} onPress={() => showPrompt((selected === "five" ? FIVE : selected === "king" ? KING : selected === "taboo" ? TABOOS : BOMBS)[gs.promptRound % 5])} /><Text style={styles.stats}>{selected === "five" ? "⏱️ 5 segundos · si fallas, bebes" : selected === "taboo" ? "No pronuncies ninguna palabra prohibida" : selected === "bomb" ? "Responde y pásala antes de la explosión" : "Las normas de grupo se acumulan"}</Text></>}
        {!["coin", "never", "truth", "probable", "five", "king", "taboo", "bomb"].includes(selected) && <><Text style={styles.prompt}>{prompt}</Text><Button label="NUEVO RETO" onPress={() => showPrompt(`${MODES.find((m) => m.id === selected)?.title}: ${MODES.find((m) => m.id === selected)?.hint}`)} /><Text style={styles.stats}>Dinámica sincronizada para toda la sala · cada acción actualiza el estado en directo.</Text></>}
      </View>
    </ScrollView>
  </View>;
}
function Button({ label, onPress, secondary }: { label: string; onPress: () => void; secondary?: boolean }) { return <Pressable onPress={onPress} style={[styles.button, secondary && styles.secondary]}><Text style={[styles.buttonText, secondary && styles.secondaryText]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ screen: { flex: 1 }, loading: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "#0A0014" }, catalog: { gap: 8 }, search: { marginHorizontal: 16, height: 42, borderRadius: 10, borderWidth: 1, borderColor: "#3A2055", backgroundColor: "#15042A", color: "#FFF", paddingHorizontal: 14, fontFamily: "Inter_400Regular" }, selector: { gap: 8, paddingHorizontal: 16, paddingBottom: 10 }, tab: { width: 112, minHeight: 78, borderRadius: 12, borderWidth: 1, borderColor: "#3A2055", backgroundColor: "#15042A", padding: 8, alignItems: "center", justifyContent: "center", gap: 4 }, activeTab: { borderColor: "#FF7A45", backgroundColor: "#FF7A4520" }, tabIcon: { fontSize: 24 }, tabText: { color: "#C9BDDB", fontFamily: "Inter_700Bold", fontSize: 10, textAlign: "center" }, activeText: { color: "#FF7A45" }, container: { width: "100%", maxWidth: 720, alignSelf: "center", padding: 16, gap: 16 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, kicker: { color: "#FF7A45", fontFamily: "Inter_700Bold", fontSize: 10, letterSpacing: 2 }, title: { fontFamily: "Inter_700Bold", fontSize: 28 }, exit: { borderWidth: 1, borderColor: "#FF2D6F", borderRadius: 9, padding: 10 }, exitText: { color: "#FF2D6F", fontFamily: "Inter_700Bold", fontSize: 11 }, game: { minHeight: 480, borderWidth: 2, borderColor: "#FF7A45", borderRadius: 20, backgroundColor: "#FF7A4516", padding: 20, alignItems: "center", justifyContent: "center", gap: 14 }, bigIcon: { fontSize: 48 }, gameTitle: { color: "#FF7A45", fontFamily: "Inter_700Bold", fontSize: 24, textAlign: "center" }, hint: { color: "#C9BDDB", fontFamily: "Inter_400Regular", fontSize: 12, textAlign: "center" }, coin: { fontSize: 76 }, prompt: { color: "#FFF", fontFamily: "Inter_600SemiBold", fontSize: 21, lineHeight: 29, textAlign: "center", maxWidth: 560 }, button: { minWidth: 220, borderRadius: 11, backgroundColor: "#FF7A45", alignItems: "center", padding: 15 }, buttonText: { color: "#180B1F", fontFamily: "Inter_700Bold", letterSpacing: 1 }, secondary: { backgroundColor: "transparent", borderWidth: 1, borderColor: "#B026FF" }, secondaryText: { color: "#B026FF" }, row: { flexDirection: "row", gap: 10, flexWrap: "wrap", justifyContent: "center" }, stats: { color: "#BDA9CF", fontFamily: "Inter_400Regular", fontSize: 12, textAlign: "center" }, switch: { flexDirection: "row", borderWidth: 1, borderColor: "#663B75", borderRadius: 10, overflow: "hidden" }, switchButton: { padding: 10 }, selectedSwitch: { backgroundColor: "#FF4F9A" }, switchText: { color: "#FFF", fontFamily: "Inter_700Bold", fontSize: 11 }, players: { flexDirection: "row", flexWrap: "wrap", justifyContent: "center", gap: 8 }, player: { borderWidth: 1, borderColor: "#49305F", borderRadius: 9, padding: 11, minWidth: 130 }, playerText: { color: "#FFF", fontFamily: "Inter_500Medium" } });