import { useGetBarajaRoom, useLeaveBarajaRoom, usePartyAction, type PartyState } from "@workspace/api-client-react";
import { useRouter } from "expo-router";
import React, { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import BoardRoomLobby from "@/components/BoardRoomLobby";
import { useColors } from "@/hooks/useColors";
import { clearBarajaSession, loadBarajaSession, type BarajaSession } from "@/lib/barajaSession";

const NEVER = ["He bebido a escondidas en una fiesta", "He mandado un mensaje y me he arrepentido", "He besado a alguien en esta sala", "He fingido estar enfermo para no salir", "He bailado encima de una mesa", "He tenido un crush con un amigo", "He roto algo y no lo he dicho", "He cantado fatal en público", "He usado una excusa para ligar", "He cotilleado un chat ajeno", "He perdido el móvil de fiesta", "He hecho una llamada borracho", "He mentido sobre mi edad", "He tenido una cita desastrosa", "He enviado un emoji equivocado", "He fingido conocer una canción", "He salido con dos personas a la vez", "He olvidado el nombre de alguien", "He bailado con un desconocido", "He hecho una apuesta absurda", "He dormido en casa de un amigo", "He dicho te quiero sin querer", "He stalkeado a un ex", "He llorado de fiesta", "He ganado una competición ridícula", "He tenido un apodo secreto", "He fingido entender una referencia", "He hecho ghosting", "He vuelto con mi ex", "He contado un secreto", "He perdido una apuesta", "He cocinado a las 4 de la mañana", "He pedido comida para todos", "He hecho karaoke solo", "He usado una app de citas", "He tenido un flechazo instantáneo", "He confundido una fecha", "He llegado tarde a mi propia fiesta", "He hecho una foto comprometida", "He bailado con un familiar", "He mentido para salir de un plan", "He tenido una risa contagiosa", "He dicho algo fuera de lugar", "He tenido una planta con nombre", "He hablado con una mascota", "He comprado algo inútil de madrugada", "He hecho una promesa imposible", "He visto una serie entera en un día", "He cambiado de look impulsivamente", "He hecho una videollamada inesperada", "He tenido un secreto durante años", "He fingido ser experto", "He cantado en la ducha", "He hecho una entrada dramática", "He olvidado una contraseña", "He dado un consejo que no sigo", "He tenido un sueño extraño", "He reído en un momento serio", "He copiado una respuesta", "He pedido perdón sin tener razón", "He hecho algo solo por una apuesta"];
const PROBABLE = ["¿Quién es más probable que llegue tarde?", "¿Quién es más probable que se enamore primero?", "¿Quién es más probable que sobreviva a un apocalipsis?", "¿Quién es más probable que olvide su propio cumpleaños?", "¿Quién es más probable que se haga viral?", "¿Quién es más probable que se vaya de viaje mañana?", "¿Quién es más probable que gane una discusión?", "¿Quién es más probable que mande un audio de 10 minutos?"];
export default function PartyRoomScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const router = useRouter();
  const [session, setSession] = useState<BarajaSession | null>(null); const [hydrated, setHydrated] = useState(false);
  useEffect(() => { loadBarajaSession().then((s) => { setSession(s); setHydrated(true); }); }, []);
  const { data: room, isLoading } = useGetBarajaRoom(session?.roomCode ?? "", session?.playerId ?? "");
  const party = usePartyAction(); const leave = useLeaveBarajaRoom();
  if (!hydrated || (session && isLoading)) return <View style={styles.loading}><ActivityIndicator color="#FF7A45" /></View>;
  if (!session || !room) return <BoardRoomLobby kind="party" title="Sala Social Party" subtitle="Dinámicas sincronizadas para reír, votar y brindar." accent="#FF7A45" maxPlayers={12} defaultMaxPlayers={6} onBack="/" />;
  const gs = room.gameState?.type === "party" ? room.gameState : null;
  if (!gs) return <View style={styles.loading}><ActivityIndicator color="#FF7A45" /></View>;
  const card = gs.promptText; const votes = Object.values(gs.promptVotes); const yes = votes.filter((v) => v === "sí").length; const no = votes.filter((v) => v === "no").length; const send = (action: "coin" | "prompt" | "vote" | "probable", value?: string, kind?: "incómoda" | "yo-nunca") => party.mutate({ code: room.code, playerId: session.playerId, action, value, kind });
  const quit = async () => { await leave.mutateAsync({ code: room.code, playerId: session.playerId }); await clearBarajaSession(); router.replace("/"); };
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.container, { paddingTop: insets.top + 18, paddingBottom: insets.bottom + 30 }]}>
    <View style={styles.header}><View><Text style={styles.kicker}>SALA SOCIAL · 18+</Text><Text style={[styles.title, { color: colors.foreground }]}>🎉 PARTY MODE</Text></View><Pressable onPress={quit} style={styles.exit}><Text style={styles.exitText}>SALIR</Text></Pressable></View>
    <View style={styles.coinCard}><Text style={styles.section}>🪙 EL JUEGO DE LA MONEDA</Text><Text style={styles.coin}>{gs.coinSide ? (gs.coinSide === "cara" ? "🙂" : "🔴") : "🪙"}</Text><Text style={styles.result}>{gs.coinSide ? `${gs.coinSide.toUpperCase()} · ${room.players.find((p) => p.id === gs.coinStarterId)?.name ?? "alguien"} empieza · Bote ${gs.sipPot} sorbo(s)` : "Lanza la moneda para asignar quién empieza"}</Text><Pressable onPress={() => send("coin")} style={styles.cta}><Text style={styles.ctaText}>LANZAR MONEDA</Text></Pressable></View>
    <View style={styles.card}><Text style={styles.section}>🔥 YO NUNCA · {gs.promptKind === "yo-nunca" ? "CALIENTE" : "RISAS"}</Text><Text style={styles.prompt}>{card ?? "Pulsa una tarjeta para empezar"}</Text><View style={styles.actions}><Pressable onPress={() => send("vote", "sí")} style={[styles.vote, { borderColor: "#FF4F9A" }]}><Text style={{ color: "#FF4F9A", fontFamily: "Inter_700Bold" }}>HE BEBIDO</Text></Pressable><Pressable onPress={() => send("vote", "paso")} style={[styles.vote, { borderColor: "#8C7BA5" }]}><Text style={{ color: "#C9BDDB", fontFamily: "Inter_700Bold" }}>PASO</Text></Pressable></View><Text style={styles.percentage}>{votes.length ? `${Math.round((yes / votes.length) * 100)}% han bebido · ${Math.round((no / votes.length) * 100)}% no` : "Votación en vivo: 0 votos"}</Text><Pressable onPress={() => send("prompt", NEVER[gs.promptRound % NEVER.length], "yo-nunca")} style={styles.secondary}><Text style={styles.secondaryText}>NUEVA TARJETA</Text></Pressable></View>
    <View style={styles.card}><Text style={styles.section}>🎡 VERDAD O RETO</Text><Text style={styles.prompt}>{gs.promptKind === "incómoda" && card ? card : "La ruleta elige una dinámica para la sala"}</Text><Pressable onPress={() => send("prompt", "VERDAD: cuenta una anécdota que nadie conozca", "incómoda")} style={styles.cta}><Text style={styles.ctaText}>VERDAD</Text></Pressable><Pressable onPress={() => send("prompt", "RETO: brinda y manda un audio cantando", "incómoda")} style={styles.secondary}><Text style={styles.secondaryText}>RETO · TRAGO</Text></Pressable></View>
    <View style={styles.card}><Text style={styles.section}>👀 QUIÉN ES MÁS PROBABLE QUE...</Text><Text style={styles.prompt}>{gs.promptKind === "incómoda" && card ? card : PROBABLE[gs.promptRound % PROBABLE.length]}</Text><View style={styles.actions}>{room.players.map((p) => <Pressable key={p.id} onPress={() => send("probable", `${PROBABLE[gs.promptRound % PROBABLE.length]} → ${p.name}`)} style={styles.playerVote}><Text style={styles.playerVoteText}>{p.avatar} {p.name}</Text></Pressable>)}</View><Text style={styles.percentage}>Votación anónima sincronizada · el más votado bebe</Text><Pressable onPress={() => send("probable", PROBABLE[(gs.promptRound + 1) % PROBABLE.length])} style={styles.secondary}><Text style={styles.secondaryText}>NUEVA PREGUNTA</Text></Pressable></View>
  </ScrollView>;
}
const styles = StyleSheet.create({ loading: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "#0A0014" }, container: { width: "100%", maxWidth: 720, alignSelf: "center", padding: 16, gap: 14 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, kicker: { color: "#FF7A45", fontFamily: "Inter_700Bold", fontSize: 10, letterSpacing: 2 }, title: { fontFamily: "Inter_700Bold", fontSize: 28 }, exit: { borderWidth: 1, borderColor: "#FF2D6F", borderRadius: 9, padding: 10 }, exitText: { color: "#FF2D6F", fontFamily: "Inter_700Bold", fontSize: 11 }, card: { borderWidth: 1, borderColor: "#3A2055", borderRadius: 16, backgroundColor: "#15042A", padding: 16, gap: 12 }, coinCard: { borderWidth: 2, borderColor: "#FF7A45", borderRadius: 16, backgroundColor: "#FF7A4515", padding: 18, alignItems: "center", gap: 10 }, section: { color: "#FFF", fontFamily: "Inter_700Bold", fontSize: 13, letterSpacing: .7 }, coin: { fontSize: 60 }, result: { color: "#D9C9E9", textAlign: "center", fontFamily: "Inter_500Medium" }, prompt: { color: "#FFF", fontFamily: "Inter_600SemiBold", fontSize: 20, lineHeight: 28, textAlign: "center", paddingVertical: 8 }, cta: { backgroundColor: "#FF7A45", borderRadius: 10, alignItems: "center", padding: 14 }, ctaText: { color: "#180B1F", fontFamily: "Inter_700Bold", letterSpacing: 1 }, actions: { flexDirection: "row", flexWrap: "wrap", justifyContent: "center", gap: 8 }, vote: { borderWidth: 2, borderRadius: 10, padding: 13, minWidth: 135, alignItems: "center" }, percentage: { color: "#BDA9CF", fontFamily: "Inter_400Regular", textAlign: "center", fontSize: 12 }, secondary: { borderWidth: 1, borderColor: "#B026FF", borderRadius: 10, alignItems: "center", padding: 12 }, secondaryText: { color: "#B026FF", fontFamily: "Inter_700Bold", letterSpacing: 1 }, playerVote: { borderWidth: 1, borderColor: "#49305F", borderRadius: 9, padding: 10, minWidth: 130 }, playerVoteText: { color: "#FFF", fontFamily: "Inter_500Medium" } });